# NodehistJ Docker Compose Configuration
#
# Сервисы:
# - minio: Хранилище файлов nodelist
# - redis: Кэширование данных
# - kafka: Очереди сообщений
# - postgres: Основная база данных
# - nodehistj-*: Микросервисы системы
#
# Требуемые переменные окружения:
# MINIO_URL, MINIO_ROOT_USER, MINIO_ROOT_PASSWORD - доступ к MinIO
# REDIS_PASSWORD - пароль Redis
# POSTGRES_USER, POSTGRES_PASSWORD - доступ к PostgreSQL
# FTP_DOWNLOAD_FROM_YEAR - год начала загрузки файлов
# GITHUB_USERNAME, GITHUB_TOKEN - для приватных зависимостей
#
# Использование:
# 1. Создать .env файл с переменными
# 2. Запустить: docker compose -f compose.yml up -d
#
# Версия: 1.0

services:
  redis:
    image: redis:alpine
    networks:
      - nodehistj
    healthcheck:
      test: redis-cli ping || exit 1
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  redpanda:
    image: redpandadata/redpanda
    restart: unless-stopped
    hostname: redpanda
    networks:
      - nodehistj
    deploy:
      resources:
        limits:
          memory: 1G
    command:
      - redpanda start
        --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
  cassandra:
    image: cassandra
    networks:
      - nodehistj
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces;"]
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 5

  # Сервис загрузки файлов nodelist с FTP
  # Основные зависимости: MinIO, Kafka
  nodehistj-download-nodelists:
    image: gavrilovegor519/nodehistj-download-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-download-nodelists
        SKIP_TESTS: "true"
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - nodehistj
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - MINIO_URL=${MINIO_URL}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    depends_on:
      redpanda:
        condition: service_healthy

  # Сервис работы с историческими данными nodelist
  # Основные зависимости: MinIO, Kafka, PostgreSQL, Redis
  nodehistj-historic-nodelists:
    image: gavrilovegor519/nodehistj-historic-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-historic-nodelists
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - nodehistj
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - MINIO_URL=${MINIO_URL}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - CASSANDRA_HOST=cassandra
    depends_on:
      redpanda:
        condition: service_healthy
      cassandra:
        condition: service_started
      redis:
        condition: service_healthy

  # Сервис работы с актуальными данными nodelist
  # Основные зависимости: MinIO, Kafka, PostgreSQL, Redis
  nodehistj-newest-nodelists:
    image: gavrilovegor519/nodehistj-newest-nodelists:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-newest-nodelists
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - nodehistj
    ports:
      - "8082:8080"
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - MINIO_URL=${MINIO_URL}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - CASSANDRA_HOST=cassandra
    depends_on:
      redpanda:
        condition: service_healthy
      cassandra:
        condition: service_started
      redis:
        condition: service_healthy

  # Сервис сравнения исторических и актуальных данных
  # Основные зависимости: Kafka, PostgreSQL, Redis
  nodehistj-history-diff:
    image: gavrilovegor519/nodehistj-history-diff:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: nodehistj-history-diff
        SKIP_TESTS: "true"
      secrets:
        - github_username
        - github_token
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - nodehistj
    ports:
      - "8083:8080"
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=redpanda:9092
      - REDIS_HOST=redis
      - MINIO_URL=${MINIO_URL}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - CASSANDRA_HOST=cassandra
    depends_on:
      redpanda:
        condition: service_healthy
      cassandra:
        condition: service_started
      redis:
        condition: service_healthy

secrets:
  github_username:
    environment: GITHUB_USERNAME
  github_token:
    environment: GITHUB_TOKEN

networks:
  nodehistj:
    driver: bridge

volumes:
  redpanda_data:
  cassandra_data: