providers:
  docker: true
entrypoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
certificatesresolvers:
  myresolver:
    acme:
      storage: /etc/traefik/acme.json
      tlsChallenge: {}