name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions: write-all

jobs:
  build-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: gradle test --warning-mode all
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./nodehistj-today-nodelist

  build-2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: gradle test --warning-mode all
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./nodelistj-download-nodelists